version: '3.9'
services:
  kafka:
    image: bitnami/kafka:3.3.1
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - /var/kafka/log:/bitnami/kafka/data/logs
      - ./configs/server.properties:/bitnami/kafka/config
      - ./logs:/var/kafka/log
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes