version: '3.9'
services:
  kafka:
    image: bitnami/kafka:3.3.1
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - ./logs:/bitnami/kafka/data/log
      - ./configs:/bitnami/kafka/config
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
