---
name: CI/CD pipeline for building MongoDB Docker image

on: 
  push:
    paths:
      - 'examples/mysql-avro-mongodb/**'
      - .github/workflows/mongodb.yaml
  pull_request:
    paths:
    - 'examples/mysql-avro-mongodb/**'
    - .github/workflows/mongodb.yaml

jobs:
  build-mongodb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short SHA
        id: vars
        run: echo "GIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./examples/mysql-avro-mongodb
          file: ./examples/mysql-avro-mongodb/Dockerfile
          push: true
          tags: |
            databurst/avro_mongodb:latest
            databurst/avro_mongodb:${{ env.GIT_SHORT_SHA }}
